package uci.cs297p.model;

import java.util.Date;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.id
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.name
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.year
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.introduction
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.picture_path
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private String picturePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.create_time
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.update_time
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.rating
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private Float rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movies.rating_number
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    private Integer ratingNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Movie(Integer id, String name, Integer year, String introduction, String picturePath, Date createTime, Date updateTime, Float rating, Integer ratingNumber) {
        this.id = id;
        this.name = name;
        this.year = year;
        this.introduction = introduction;
        this.picturePath = picturePath;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.rating = rating;
        this.ratingNumber = ratingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Movie() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.id
     *
     * @return the value of movies.id
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.id
     *
     * @param id the value for movies.id
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.name
     *
     * @return the value of movies.name
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.name
     *
     * @param name the value for movies.name
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.year
     *
     * @return the value of movies.year
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.year
     *
     * @param year the value for movies.year
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.introduction
     *
     * @return the value of movies.introduction
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.introduction
     *
     * @param introduction the value for movies.introduction
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.picture_path
     *
     * @return the value of movies.picture_path
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.picture_path
     *
     * @param picturePath the value for movies.picture_path
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.create_time
     *
     * @return the value of movies.create_time
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.create_time
     *
     * @param createTime the value for movies.create_time
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.update_time
     *
     * @return the value of movies.update_time
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.update_time
     *
     * @param updateTime the value for movies.update_time
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.rating
     *
     * @return the value of movies.rating
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Float getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.rating
     *
     * @param rating the value for movies.rating
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setRating(Float rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movies.rating_number
     *
     * @return the value of movies.rating_number
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public Integer getRatingNumber() {
        return ratingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movies.rating_number
     *
     * @param ratingNumber the value for movies.rating_number
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    public void setRatingNumber(Integer ratingNumber) {
        this.ratingNumber = ratingNumber;
    }
}