package uci.cs297p.model;

import uci.cs297p.model.Movie;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    int insertSelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    Movie selectByPrimaryKey(Integer id);

    List<Movie> selectBySearch(@Param("keyWords") String keyWords);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    int updateByPrimaryKeySelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movies
     *
     * @mbggenerated Sun Nov 18 20:31:56 PST 2018
     */
    int updateByPrimaryKey(Movie record);
}