package uci.cs297p.model;

import uci.cs297p.model.UMRelation;
import uci.cs297p.model.UMRelationKey;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UMRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:40:00 PST 2018
     */
    int deleteByPrimaryKey(UMRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:40:00 PST 2018
     */
    int insert(UMRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:40:00 PST 2018
     */
    int insertSelective(UMRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:40:00 PST 2018
     */
    UMRelation selectByPrimaryKey(UMRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:40:00 PST 2018
     */
    int updateByPrimaryKeySelective(UMRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:40:00 PST 2018
     */
    int updateByPrimaryKey(UMRelation record);

    List<UMRelation> getCollectionsByUserId(Integer userId);
}