package uci.cs297p.model;

public class UMRelationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_m_relation.movie_id
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    private Integer movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_m_relation.user_id
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public UMRelationKey(Integer movieId, Integer userId) {
        this.movieId = movieId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public UMRelationKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_m_relation.movie_id
     *
     * @return the value of u_m_relation.movie_id
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_m_relation.movie_id
     *
     * @param movieId the value for u_m_relation.movie_id
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_m_relation.user_id
     *
     * @return the value of u_m_relation.user_id
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_m_relation.user_id
     *
     * @param userId the value for u_m_relation.user_id
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "UMRelationKey{" +
                "movieId=" + movieId +
                ", userId=" + userId +
                '}';
    }
}