package uci.cs297p.model;

public class UMRelation extends UMRelationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_m_relation.collected
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    private Integer collected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_m_relation.rating
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    private Integer rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public UMRelation(Integer movieId, Integer userId, Integer collected, Integer rating) {
        super(movieId, userId);
        this.collected = collected;
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_m_relation
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public UMRelation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_m_relation.collected
     *
     * @return the value of u_m_relation.collected
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public Integer getCollected() {
        return collected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_m_relation.collected
     *
     * @param collected the value for u_m_relation.collected
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public void setCollected(Integer collected) {
        this.collected = collected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_m_relation.rating
     *
     * @return the value of u_m_relation.rating
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_m_relation.rating
     *
     * @param rating the value for u_m_relation.rating
     *
     * @mbggenerated Mon Nov 26 18:56:23 PST 2018
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    @Override
    public String toString() {
        return "UMRelation{" +
                "collected=" + collected +
                ", rating=" + rating +
                '}';
    }
}